### ISSUE TITLE
Name/dates input function

### ISSUE THREAD

**Issue by melliott7264** [melliott7264/vacation-planner#4]
This issue involves creating the function(s) to input the trip name and start and end dates  and save them to local storage.
- Will need to setup an array/object data structure to save multiple trip plans and multiple (up to 8 (including the current day)) days/locations for each plan.
- End date must be validated to be within 7 days of the current date.
- Dates used for searches must be in the format YYYYMMDD?.
- Dates to be displayed must be in the format MM/DD/YY?
- LocalStorage save and load functions need to be part of this issue.
- Must use Jquery UI datepicker to select start and end dates.
- Name and dates must be submitted by clicking a submit button.

**Comment by ThomasCsk** [comment]
Managed to get it done. Let me know if I need to change anything on it.
